### ISSUE TITLE
Pre-compilation fails

### ISSUE THREAD

**Issue by MaximilianJHuber** [FixedEffects/FixedEffectModels.jl#105]
On a Win10Pro virtual machine, Julia 1.4.2, empty environment, empty `.../.julia/compiled/v1.4/` and `.../.julia/packges/v1.4/`  folders, I run:
```
import Pkg;
Pkg.add("FixedEffectModels")
Pkg.precompile()
```
The required packages appear in `.../.julia/compiled/v1.4/`, e.g. `DataFrames`, with a `.ji` inside the folder. But `FixedEffectModels` remains **empty**. `precompile` does not throw an error. `FixedEffectModels`s version is `0.10.7`.

When `using FixedEffectModels` the pre-compilation happens again, skipping the required packages, and throwing:

```
[ Info: Precompiling FixedEffectModels [9d5cd8c9-2029-5cab-9928-427838db53e3]
ERROR: Failed to precompile FixedEffectModels [9d5cd8c9-2029-5cab-9928-427838db53e3] to C:\Users\USER\.julia\compiled\v1.4\FixedEffectModels\XFTup_4iU8P.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
```

On my Win10 PC, same setup, there is **no error**. 

Please, close this issue if you think this is not related to `FixedEffectModels`, but it is strange that other packages pre-compile just fine.

**Comment by matthieugomez** [comment]
Not sure why. I used to do something a bit unorthodox but I've removed it (https://github.com/FixedEffects/FixedEffectModels.jl/pull/106). If this still does not work, Im not sure what's happening.
