### ISSUE TITLE
Supporting  instruments for interactions between FE and endogenous variables

### ISSUE THREAD

**Issue by paul-huebner** [FixedEffects/FixedEffectModels.jl#118]
Hi Matthieu,

Is it currently possible to instrument for interactions between fixed effects and additional (endogenous) variables?

For instance following the example in the README.md file, can we estimate separate slopes for price per state, while at the same time instrumenting for price ? I.e. something like

`reg(df, @formula(Sales ~ (fe(State)&Price ~ fe(State)&Pimin)))`

I'm new to FixedEffectModels (and Julia more generally) so I might really just get the syntax wrong...

**Comment by matthieugomez** [comment]
You cannot use high-dimensional fixed effects in this case, but you can use regular categorical variables, i.e.,
```
using CategoricalArrays
df.Statec = categorical(df.State)
reg(df, @formula(Sales ~ (Statec&Price ~ Statec&Pimin)))
```
