### ISSUE TITLE
@model not defined

### ISSUE THREAD

**Issue by grandemundo82** [FixedEffects/FixedEffectModels.jl#12]
Using Juila 0.5.2. I get the following when running 

`using DataFrames, RDatasets, FixedEffectModels`
`df = dataset("plm", "Cigar")`
`df[:StatePooled] =  pool(df[:State])`
`df[:YearPooled] =  pool(df[:Year])`
`reg(df, @model(Sales ~ NDI, fe = StatePooled + YearPooled, weights = Pop, vcov = cluster(StatePooled)))`

ERROR: UndefVarError: @model not defined

**Comment by matthieugomez** [comment]
The README file refers to the version of FixedEffectModels v0.4.0 available on Julia 0.6
