### ISSUE TITLE
Support for `coeftable` 

### ISSUE THREAD

**Issue by pdeffebach** [FixedEffects/FixedEffectModels.jl#125]
it would be nice to have `coeftable`, since it's an object I know how to work with. 

I'm not sure which StatsModels abstractions are missing more generally but this one would be nice to have.

**Comment by pdeffebach** [comment]
Update: I have realized that this isn't a very good issue. The structure of `coeftable` is an implementation detail and I shouldn't expect it to be consistent across regression packages. 

Nonetheless it would be nice if you exported `coeftable` since it's part of the public API for statistical models.

**Comment by matthieugomez** [comment]
I forgot to re-export it. Fixed in  https://github.com/FixedEffects/FixedEffectModels.jl/pull/126 

Also, coeftable used to return a CoefTable2, a modified type allowing to display more results. It now returns a CoefTable, consistent with StatsBase docs

**Comment by pdeffebach** [comment]
Wonderful, thanks! I've moved to this package after GLM since now my metrics problem sets require clustering, I will file issues as needed!
