### ISSUE TITLE
Bounds Error

### ISSUE THREAD

**Issue by OGiesecke** [FixedEffects/FixedEffectModels.jl#169]
I am running into a BoundsError: attempt to access 15-element BitVector at index. Is this a known problem. If so, is there already a workaround?

**Comment by OGiesecke** [comment]
I think it happens when there are more instruments passed then eventually used in the estimation.

**Comment by matthieugomez** [comment]
could you share a reproductible example?

**Comment by OGiesecke** [comment]
I can't really share the concrete example here but my analysis has show that the problem occurs if you have a set of endogenous variables; some of them missing. You run into the bound error if you have a set of instruments that are populated also for those observations for which the endogenous variables are missing. I hope this is concrete enough.

**Comment by matthieugomez** [comment]
Could you report the full trace?
