### ISSUE TITLE
Storing via save = true

### ISSUE THREAD

**Issue by felixholub** [FixedEffects/FixedEffectModels.jl#17]
I'm failing to access stored fixed effects. But also for example predictions do not work. Do I apply `save=true` incorrectly?
```
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
df[:StatePooled] =  pool(df[:State])
df[:YearPooled] =  pool(df[:Year])
model =  @model(Sales ~ NDI, fe = StatePooled + YearPooled, save = true)
result = reg(df,model)
show(result)
predict(result,df)
```
yields
` predict is not defined by default for fixed effect models.  Run reg with the the option save = true `

**Comment by matthieugomez** [comment]
Try `result.augmentdf`. I agree that the error should be a bit more informative.

**Comment by felixholub** [comment]
Thank you!
