### ISSUE TITLE
Lag/Lead Operators in @formula

### ISSUE THREAD

**Issue by junder873** [FixedEffects/FixedEffectModels.jl#193]
Maybe this is an issue with StatsModels.jl, but I was wondering if there is a plan to allow lag and lead operators in formula (similar to R [fixest](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html)). Originally I was going to post this in StatsModels.jl, since it doesn't seem like any Julia regression package implements lag/lead right now, but I saw [this pull request](https://github.com/FixedEffects/FixedEffectModels.jl/pull/109) that seemed to suggest it was in this package.

**Comment by matthieugomez** [comment]
I want to wait until Julia has a better lag function
https://github.com/JuliaArrays/ShiftedArrays.jl/pull/37
For now, simply create the variable before generating the formula.

**Comment by eloualiche** [comment]
Closing this as lead/lag should be implemented in a separate package. 
This outside of the scope of fixedeffectmodels. 

We have posted on shiftedarrays for this feature; hopefully we will find a way to implement it in the future.
