### ISSUE TITLE
Is predict working?

### ISSUE THREAD

**Issue by alfaromartino** [FixedEffects/FixedEffectModels.jl#194]
I saw that `predict` was updated, but it's not working for me.  I'm running a regression with `save=:all` or `save=:fe`, and using `predict(ols1,df)`, where `ols1` is the model and `df` the dataframe used for estimation. But I get 
"predict is not defined for fixed effect models. To access the fixed effects, run `reg` with the option save = :fe, and access fixed effects with `fe()`"

I tried updating `FixedEffectModels`, but it didn't solve the problem. I'm using the version 1.6.4.
Thanks

**Comment by matthieugomez** [comment]
It will work once 1.6.5 is released
https://github.com/JuliaRegistries/General/pull/56400
