### ISSUE TITLE
how to get within r2 and t value from fixedeffectmodel?

### ISSUE THREAD

**Issue by zdlspace0528** [FixedEffects/FixedEffectModels.jl#200]
how to get within r2 and t value from fixedeffectmodel? and how to show intercept term in the table?

**Comment by matthieugomez** [comment]
You can do `m.r_within` and `StatsAPI.coeftable(m)`. For now, you cannot show the intercept term in the table (it's an open issue)

**Comment by zdlspace0528** [comment]
Thanks very much. I hope that you can add an option, such as “constant = true” or “constant = false”. 
Then we can choose to report  or not report intercept term by ourself.
In another package `Econometrics.jl`, it also report intercept term.


Raymond


| |
张德亮
|
|
***@***.***
|


---- Replied Message ----
| From | Matthieu ***@***.***> |
| Date | 06/29/2022 00:49 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [FixedEffects/FixedEffectModels.jl] how to get within r2 and t value from fixedeffectmodel? (Issue #200) |

You can do m.r_within and StatsAPI.coeftable(m). For now, you cannot show the intercept term in the table (it's an open issue)
