### ISSUE TITLE
upgrade to dataframes v0.11.4

### ISSUE THREAD

**Issue by floswald** [FixedEffects/FixedEffectModels.jl#21]
salut @matthieugomez 

is there anything that's holding you back from upgrading to dataframes v0.11 (other than the job market :-)  )
as you know v0.11 this is a major step forward, and I have `FixedEffectModels.jl` as a blocking dependency in a couple of projects.

cheers
f

**Comment by floswald** [comment]
ping @jmboehm

**Comment by matthieugomez** [comment]
Done. https://github.com/JuliaLang/METADATA.jl/pull/13164
