### ISSUE TITLE
MethodError: no method matching fe(::CategoricalValue{String15, UInt32})

### ISSUE THREAD

**Issue by jariji** [FixedEffects/FixedEffectModels.jl#211]
I'm not sure how to reproduce this, but `fit`ting a model like `y ~ a + b + fe(s)` where `s` refers to a `String` column or a `CategoricalArray` fails with a MethodError:

```
ERROR: MethodError: no method matching fe(::CategoricalValue{String15, UInt32})
```

The same occurs if I explicitly use `FixedEffectModels.fe` in the formula.

**Comment by matthieugomez** [comment]
I can't reproduce this. 
```julia
using DataFrames, FixedEffectModels
y = rand(10)
x = rand(10)
id = repeat(["1", "2"], inner = 5)
df = DataFrame(y = y, x = x, id = id)
reg(df, @formula(y~x + fe(id)))
```

**Comment by jariji** [comment]
I'll reopen if I can get a minimal example.
