### ISSUE TITLE
Implement StatsAPI.fit() 

### ISSUE THREAD

**Issue by jariji** [FixedEffects/FixedEffectModels.jl#212]
`StatsAPI` provides `fit` for fitting a statistical model which is used by StatsBase.jl, GLM.jl, and Econometrics.jl. It would be convenient if FixedEffects.jl used this as well so I could just learn the one API.

**Comment by matthieugomez** [comment]
Sure, here is the pull request: https://github.com/FixedEffects/FixedEffectModels.jl/pull/216
