### ISSUE TITLE
Feature request: GPU support in MacOS

### ISSUE THREAD

**Issue by moshialam** [FixedEffects/FixedEffectModels.jl#217]
Hi 
The new Macs have quite a few GPUs which can be used to make computation orders of magnitude faster. However the current support of FixedEffects.jl only works with NVIDIA GPUs. Are there plans in the near future to make use to the GPUs in Macs? It will be extremely useful!
Thanks!

**Comment by matthieugomez** [comment]
Agreed! However, Metal.jl does not support atomics yet (i.e. the `atomic_add!` function, which is at the core of the algorithm). I will have another look once it does. See https://github.com/JuliaGPU/Metal.jl/issues/79

**Comment by matthieugomez** [comment]
The package now supports Mac GPUs it but it ends up being slower than CPUs. If anyone is interested in making this faster, the relevant code is https://github.com/FixedEffects/FixedEffects.jl/blob/master/ext/MetalExt.jl
