### ISSUE TITLE
How can I get the dof?

### ISSUE THREAD

**Issue by xiaobaaaa** [FixedEffects/FixedEffectModels.jl#227]
I want to get the dof of a model, but there is an ERROR: type FixedEffectModel has no field dof.
``` julia
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
result = reg(df, @formula(Sales ~ NDI + fe(State) + fe(Year)), Vcov.cluster(:State), weights = :Pop)
result.dof
```

**Comment by xiaobaaaa** [comment]
Sorry, I update the package, problem solved.

**Comment by matthieugomez** [comment]
The function dof will be exported to avoid having to access internal fields like this
