### ISSUE TITLE
Demeaning

### ISSUE THREAD

**Issue by friosavila** [FixedEffects/FixedEffectModels.jl#232]
Hi there
Is there any way to use the package to obtain demeaned variables?
for example, in Stata you have the hdfe utility (used to be part of reghdfe), in R you have demean function within fixest.
Is there an equivalent in Julia and  this package?
Thank you

**Comment by matthieugomez** [comment]
Yes, you should look at https://github.com/FixedEffects/FixedEffects.jl

**Comment by matthieugomez** [comment]
Actually if you want to have a similar syntax as the package, you can also use `partial_out` (type `?partial_out` to learn more about it).

**Comment by friosavila** [comment]
Thank you!
Yes this is what I needed
