### ISSUE TITLE
updates to internal representation and parsing of formulae in statsmodels v0.2.4

### ISSUE THREAD

**Issue by kleinschmidt** [FixedEffects/FixedEffectModels.jl#24]
[Version 0.2.4 of statsmodels](https://github.com/JuliaStats/StatsModels.jl/releases/tag/v0.2.4) changes when formula parsing happens.  Syntactic transformations happen at "compile time", when `@formula` is called, rather than when constructing `Terms`.  There are a few places here where an un-parsed formula expression could be passed to the `Terms` constructor, which will fail on 0.2.4.  To get around this, you could do one of three things:

1. Use`@eval` to call the formula macro: `Terms(@eval @formula $nothing ~ $rhs)`
2. Call `StatsModels.parse!` on the expression, before constructing a `Formula`, although you may need to wrap it in a call to `~` to ensure that all the syntactic rules are applied correctly, a la `StatsModels.parse!( :(~($rhs)) )`.
3. To avoid the deprecated 2-argument constructor, use the 4-argument Formula constructor, a la
    ```
    ex_orig = :($nothing ~ $rhs)
    ex = StatsModels.parse!(deepcopy(ex))
    lhs, rhs = ex.args[2:3]
    f = Formula(ex_orig, ex, lhs, rhs)
    ```

2 and 3 will work for now, but in the future the macro step will do more radical transformations of the formula (but the internal structure of the formula and terms structs will also change at that point).

**Comment by matthieugomez** [comment]
Thanks for the help! Solved with https://github.com/matthieugomez/FixedEffectModels.jl/commit/6dd13d1c22f94b3e7dbc4942868f9424b78916db
Btw, I was scared that the kind of formula I use for instrument variables `@formula(y ~ x + (x2 ~ z))` would not be parsed correctly by your new macro. But it still works well, so thanks for that. I hope this will still work even after your future changes.

**Comment by kleinschmidt** [comment]
No problem! One of the goals of that rewrite (and of the changes I have planned for the future) was to deal with nested formulae like that more cleanly.

**Comment by kleinschmidt** [comment]
It might be worth also tagging a version that puts an upper bound on StatsModels v0.2.3 (JuliaLang/METADATA.jl#14404)
