### ISSUE TITLE
small speed improvements

### ISSUE THREAD

**Issue by Ken-B** [FixedEffects/FixedEffectModels.jl#26]
Hi,
I'm working on a somewhat larger model (~100m lines, 10 columns and IV) and I've found a few speed improvements that I use myself. Maybe you can use it for inspiration. Let me know if you think any of these could use a PR and I'll make one:
* I preprocess my data so missing data are removed, but still on v0.6 checking `completecases` sometimes goes over the full dataframe (fixed for julia v0.7) [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/6dd13d1c22f94b3e7dbc4942868f9424b78916db/src/reg.jl#L109).
* With a few 10Gb's of data, I've found that copying it takes quite some time. Even in the case of no missing values, a full copy is made [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/6dd13d1c22f94b3e7dbc4942868f9424b78916db/src/reg.jl#L128).
* I've found I can speed up a bit the fixed effect multiplication by adding `Threads.@threads` in front of some of the for loops like [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/6dd13d1c22f94b3e7dbc4942868f9424b78916db/src/fixedeffect/FixedEffectProblem_LSMR.jl#L122)

On 16 threads these adaptions reduce the processing time by over half on my use case.
Cheers

**Comment by matthieugomez** [comment]
Interesting. Maybe I should have a thread option. 

Out of curisity, have you tried adding `@inbounds` in the for loop of `A_mul_B_helper` and `A_mul_B_helper`? Does it make a difference?
