### ISSUE TITLE
test fail randomly when using threads 

### ISSUE THREAD

**Issue by Ken-B** [FixedEffects/FixedEffectModels.jl#28]
My suggestion to use threads in #26 was apparently not such a good idea. When I run julia with more than 1 thread , the tests always fail and this at a different coefficient test (haven't seen it go beyond the simple tests). By looking at the code I don't see any race condtions, but I'm no expert.

I don't know if travis allows it, but perhaps you can add `JULIA_NUM_THREADS=2 julia` to the travis configuration [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/806f1199aefa4be2b8fa67a4251884b0226514e0/.travis.yml#L7)?

I will run single threaded for now.

**Comment by matthieugomez** [comment]
Ok. I am just going to remove threads. I'll have another look when it is not in beta. https://github.com/matthieugomez/FixedEffectModels.jl/commit/0e36a3d14739b547057368b3652664cd5d5db96b
