### ISSUE TITLE
Two-way clustering error when negative elements on vcov diagonal?

### ISSUE THREAD

**Issue by pbaylis** [FixedEffects/FixedEffectModels.jl#3]
Just discovered this project today. It's fantastic. Unbelievably fast.

I'm getting the following error (full error attached as errortext.txt) when doing two-way clustering.
DOMAINERROR: sqrt will only return a complex result if called with a complex argument. 

I suspect it's due to the vcov matrix not being positive semi-definite, as sometimes occurs with two way clustering. CGM (2011) mention this issue and describe a fix (pp. 241-242). I think reghdfe implements the fix but includes a warning message? Can't quite remember. I would give it a shot but I just started using Julia so I'm pretty sure I'd muck it up.

Here's a link to a gist that has the MWE and dataset, plus the full error. 
https://gist.github.com/pbaylis/66a8ef7869bb23ca5b90

Sorry, this is a silly way to attach these files.

**Comment by matthieugomez** [comment]
It seems like the error come from the degree of freedom: one group has only one observation. In this case, I take the maximum of the df and 1 in the last versions of the package.

This fix is not implemented in the version of the package in METADATA. Could you try with `Pkg.clone("https://github.com/matthieugomez/FixedEffectModels.jl")`?

**Comment by pbaylis** [comment]
My mistake, I'm having no issues with the latest version on github. I thought I had updated it, but must have had the METADATA package still active in my test session. Thanks again!

**Comment by matthieugomez** [comment]
Thanks a lot for the bug report anyway. It's very helpful at this stage.

**Comment by matthieugomez** [comment]
So don't hesitate to start issues in the future
