### ISSUE TITLE
Dropping singletons for DoF correction

### ISSUE THREAD

**Issue by jmboehm** [FixedEffects/FixedEffectModels.jl#36]
We should probably implement an option to iteratively drop singletons for the calculation of standard errors. See [this note by @sergiocorreia](http://scorreia.com/research/singletons.pdf). Since `reghdfe` has kind of become the industry standard, we should be able to match its standard errors.

**Comment by matthieugomez** [comment]
I have done it since v0.5.3 , see https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/src/reg.jl#L120
But get back to me if the command does not drop singletons in some cases.
