### ISSUE TITLE
MethodError when LHS is not a Float

### ISSUE THREAD

**Issue by pbaylis** [FixedEffects/FixedEffectModels.jl#4]
I get a MethodError when the LHS is not a float. Error is as follows:
"ERROR: MethodError: `convert` has no method matching convert(::Array{Int64,1}, :
:Type{Float64})
 in reg at C:\Users\pbaylis.julia\v0.4\FixedEffectModels\src\reg.jl:159
 in reg at C:\Users\pbaylis.julia\v0.4\FixedEffectModels\src\reg.jl:64"

MWE to reproduce:

```
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
df[:SalesInt] = round(Int64, df[:Sales])
reg(SalesInt ~ Price, df) # Error
df[:SalesIntFloat] = float(df[:SalesInt])
reg(SalesIntFloat ~ Price, df) # Works
```

Probably has to do with some syntax change in convert(). I think this could be fixed by replacing convert( ) in reg.jl:159 with float( )? My workaround is to do that before calling reg.

(Hopefully this is an actual issue. I pulled the most recent version of the package this time.)

**Comment by matthieugomez** [comment]
Thanks! The current line did not make sense. Added a test.
