### ISSUE TITLE
Possible bug handling variables with very large numbers

### ISSUE THREAD

**Issue by dgcbritto** [FixedEffects/FixedEffectModels.jl#40]
Hi,
I've been running regressions while controlling for high order polynomials on wage. When the order was too high (from the fourth), some of the coefficient were set to zero or not estimated. I rerun the regressions after scaling down the polynomial controls by a constant factor and the regression goes through.

To see the issue, you can run the code:

```julia
using DataFrames, FixedEffectModels
df = DataFrame(randn(Float64, (10000,2))*1000)
df[:x3] = map( x-> x^2,df[:x2] )
df[:x4] = map( x-> x^3,df[:x2] )
df[:x5] = map( x-> x^4,df[:x2] )

## Not all coefficients are estimated
reg(df, @model(x1 ~ x2+x3+x4+x5 ))

## Scaling down variables with very large numbers solve the issue
df[:x4] = df[:x4] * .0001
df[:x5] = df[:x5] * .0000001

reg(df, @model(x1 ~ x2+x3+x4+x5 ))
```

**Comment by matthieugomez** [comment]
Interesting.  I think it would be even worse with weights. Not sure how to handle this. Maybe use log wage ;)?

**Comment by dgcbritto** [comment]
That could work too.

I'm scaling down the variables with large values and the regression goes through just fine, the (scalled back) coefficient are just the same that you get on official stata commands. This issue bugged me for a while and I couldn't understand why some coefficients were not being estimated. I've thought about sharing it as others may face the similar issues.

Feel free to close the issue!

**Comment by matthieugomez** [comment]
No, it is an important issue. I just don't know how to solve it.

**Comment by dgcbritto** [comment]
Ok!

________________________________
De: Matthieu Gomez <notifications@github.com>
Enviado: quarta-feira, 17 de outubro de 2018 13:03
Para: matthieugomez/FixedEffectModels.jl
Cc: dgcbritto; Author
Assunto: Re: [matthieugomez/FixedEffectModels.jl] Possible bug handling variables with very large numbers (#40)

No, it is an important issue. I just don't know how to solve it.

**Comment by matthieugomez** [comment]
There was a problem in how the rank of the matrix was determined. I have pushed a new commit https://github.com/matthieugomez/FixedEffectModels.jl/commit/8702b2e9f58d67c74ec333911e737c31653322c7 that should take care of these cases. Please let me know if you encounter other issues.

**Comment by dgcbritto** [comment]
Great, thanks. I'll let you know if I find anything else.


________________________________
De: Matthieu Gomez <notifications@github.com>
Enviado: sábado, 8 de dezembro de 2018 21:06
Para: matthieugomez/FixedEffectModels.jl
Cc: dgcbritto; Author
Assunto: Re: [matthieugomez/FixedEffectModels.jl] Possible bug handling variables with very large numbers (#40)


There was a problem in how the rank of the matrix was determined. I have pushed a new commit 8702b2e<https://github.com/matthieugomez/FixedEffectModels.jl/commit/8702b2e9f58d67c74ec333911e737c31653322c7> that should take care of these cases. Please let me know if you encounter other issues.
