### ISSUE TITLE
Can we choose the 'Leave out' category for FixedEffectModels.jl?

### ISSUE THREAD

**Issue by dwmmclaughlin** [FixedEffects/FixedEffectModels.jl#43]
Hi Matthieu and FixedEffectModels dev team,

As a resource-constrained graduate student, I think being able to run fixed effects models in Julia is a wonderful idea. Thank you so much for your time and effort putting this together.

My question is, "Is there a way to choose the value of a Categorical variable when using FixedEffectModels.jl as the 'leave out' category?"  I am running an event study regression and I would like to leave out the -1 time period, but FixedEffectsModels.jl always chooses the earliest value (in my case -79).

Sorry for the StackOverflow-like question, I just wanted to know if there was functionality for choosing the leave out category.

Thanks so much for your help.

Best,

Dave

**Comment by matthieugomez** [comment]
The model is constructed using StatsModels. I think StatsModels takes the first level as the base level. You can reorder the levels of a CategoricalArray using `levels!`, see 
 http://juliadata.github.io/CategoricalArrays.jl/stable/using.html

**Comment by dwmmclaughlin** [comment]
Hi Matthieu,

Thanks so much for getting back to me.  I tried what you suggested with the following script on a fake dataset, and I put the code below:

`
### Reading in packages
using DataFrames, RDatasets, FixedEffectModels, Feather, CategoricalArrays

### Reading in dataset
@time dt = Feather.read("C:/juliaTest/dt.feather")

### Converting all variables to categorical
dt[:date] = categorical(dt[:date])
dt[:event_time] = categorical(dt[:event_time])
dt[:store_id] = categorical(dt[:store_id])
dt[:after_treat] = CategoricalArray(dt[:after_treat])

### Attempting to make 1 the base category of after_treat
dt[:after_treat] = levels!(dt[:after_treat], [1,0])
levels(dt[:after_treat])
reg(dt, @model(q~after_treat, fe=store_id+date, vcov=cluster(store_id)))

### Attempting to make 0 the base category of after_treat
dt[:after_treat] = levels!(dt[:after_treat], [0,1])
levels(dt[:after_treat])
reg(dt, @model(q~after_treat, fe=store_id+date, vcov=cluster(store_id)))
`
It looks as though using the levels!() switches the order in which the categorical levels appear in the post FixedEffectModels.jl table, but it is not switching the omitted category.  Do you have any other ideas on how to switch the base category?

Again, thanks so much for your help and I will let others in my department know about this awesome and efficient fixed effects package.

Best,

Dave

David McLaughlin
Ph.D. Candidate
University of California at Berkeley
College of Natural Resources
Department of Agricultural and Resource Economics

**Comment by matthieugomez** [comment]
So I asked around, and I don't think it is possible. I would define the `after_treat` manually if I were you.

**Comment by matthieugomez** [comment]
Ok I have added an option to do it in the [last commit](https://github.com/matthieugomez/FixedEffectModels.jl/commit/bb1ea8c2d8d55c28c24b21c617580a8fbaf2075c)
```julia
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
df[:StateC] =  categorical(df[:State])
reg(df, @model(Sales ~ YearC), contrasts = Dict(:YearC => DummyCoding(base = 80)))
```

**Comment by dwmmclaughlin** [comment]
Thanks so much, Mattieu.  I really appreciate your time an effort in updating your package.  I have already shared this package with several students in my cohort.

I updated the FixedEffectModels package in Julia, and tried to run your code, but I received the following error: "ERROR: UndefVarError: DummyCoding not defined".

Does this mean I didn't get the latest package?  Or is there something else afoot?

Best,

Dave

**Comment by matthieugomez** [comment]
use `pkg> checkout FixedEffectModels` to update to the last commit.

**Comment by dwmmclaughlin** [comment]
Awesome.  I got it working on my machine and I have it working.

Thanks so much for your help, Matthieu.  I am very grateful and I'll be sure to promote your package as a super-fast Julia implementation of fixed effect models among the students at Berkeley.

Best,

Dave
