### ISSUE TITLE
Dropping observations concerning singleton category?

### ISSUE THREAD

**Issue by MaximilianJHuber** [FixedEffects/FixedEffectModels.jl#47]
Why do you drop observations where one fixed effect is a singleton category, [here](https://github.com/matthieugomez/FixedEffectModels.jl/blob/d8fe2bd4be6d27b4b53acc9d9412e1eab1363164/src/reg.jl#L130)?

I am running a regression of wage on worker and firm fixed effects. Dropping all singletons is an overkill here, and just making sure the sample is a connected set is enough. Maybe introduce an argument to `reg` that can switch this off?

**Comment by matthieugomez** [comment]
It is mainly a way to get correct standard errors(see http://scorreia.com/research/singletons.pdf). I have just added a `drop_singletons` option however, https://github.com/matthieugomez/FixedEffectModels.jl/commit/7eb799769531d60f7b1da882f0fbc2ace2c52175

**Comment by MaximilianJHuber** [comment]
I see, thank you!
