### ISSUE TITLE
Benchmarks should use the same data to eliminate potential confounding due to pseudorandom number generator differences

### ISSUE THREAD

**Issue by wbuchanan** [FixedEffects/FixedEffectModels.jl#5]
You generate three different datasets and try to "benchmark" performance using different datasets.  Instead, you should generate a single data set and use the estimation commands from the three different platforms with the same data.  Right now it isn't clear if the differences are due to differences in estimation performance or if the underlying data was different in a way that allowed convergence to occur more easily.

**Comment by matthieugomez** [comment]
Even better: rerun the whole code 100 times and do a ttest. You'll actually find the same results : execution times are similar across different randomly generated datasets.
