### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by matthieugomez** [FixedEffects/FixedEffectModels.jl#51]
- [x] Add more tests that residuals and fixedeffects are correct in the case of IV, weights, subsets in [RegressionResult](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/test/RegressionResult.jl).

- [ ] Check that standard errors and F-stat are similar to `ivreg2, small`in [reg](https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/test/reg.jl).

**Comment by duncanhobbs** [comment]
Do you still need someone to help write tests? I don't have a lot of experience with Julia, but I would be happy to try and help.

**Comment by matthieugomez** [comment]
Yes. That would be really appreciated!  It would be nice to check that the values of fixedeffects, r2, and other statistics match the ones given from  Stata `reghdfe`. I've written some test in test/RegressionResult but it would be nice to have some tests for weights, subset & missing observations.
