### ISSUE TITLE
Instrumental Variable Interactions

### ISSUE THREAD

**Issue by junder873** [FixedEffects/FixedEffectModels.jl#57]
When trying to run a regression where the Instrumental Variable has an interaction (which I am trying to do when replicating Chang et. al (2015) ([link to paper](https://academic.oup.com/rfs/article-abstract/28/1/212/1680962?redirectedFrom=fulltext)) when I try to run
```
reg(dropmissing(df2, :Jun), @model(Jun ~ 1 + rc + (D~tau)*(1+rc)))
```
it gives the error
```
MethodError: no method matching length(::Expr)
```
I can share the data with you if needed. The data I have does not perfectly match the paper, but running the regression in R yields results that are close to the paper's results.

Overall, thank you for this package, it really is incredible.

**Comment by matthieugomez** [comment]
If I understand your question correctly, I think you need to replace `(D~tau)*(1+rc)` by `D * rc ~ tau * rc`.

**Comment by junder873** [comment]
That did mostly solve it, I think I understand the equation better now. I am still having a little bit of an issue with it dropping a degree of freedom and therefore changing the estimate where R doesn't.

Thank you for your quick reply.
