### ISSUE TITLE
F-Statistic Calculation

### ISSUE THREAD

**Issue by junder873** [FixedEffects/FixedEffectModels.jl#60]
When running a regression, I get very different F-Stats with FixedEffectModels vs. other programs. Running a simple OLS (in one set of data) get an F-Stat of about 2000, in R or using the Julia GLM package, the result is about 900. I looked into this issue, and I think the calculation for the F-Stat is wrong. In vcov/utils.jl currently:
```julia
    F = (Diagonal(coefF) * (matrix_vcov \ Diagonal(coefF)))[1]
    df_ans = df_FStat(vcov_method_data, vcov_data, hasintercept)
    dist = FDist(nobs - hasintercept, max(df_ans, 1))
```
But I have never seen F-stats calculated this way. Most methods estimate a new model (with only the intercept) and compare the standard error. This is not ideal, so based on this stackoverflow question and [answer](https://stats.stackexchange.com/questions/68151/how-to-derive-variance-covariance-matrix-of-coefficients-in-linear-regression), I think these three lines should be
```julia
    F = ((coefF' * matrix_vcov^(-1) * coefF)/length(coefF))
    df_ans = df_FStat(vcov_method_data, vcov_data, hasintercept)
    dist = FDist(length(coefF), df_ans)
```
The first part is essentially

<br /><span class="math display"><em>F</em> = <em>β</em>′(<em>σ</em>(<em>X</em>′<em>X</em>)<sup> − 1</sup>)<sup> − 1</sup><em>β</em></span><br />
Doing this makes it match the GLM package and regressions in R (including for felm).

Changing the distribution is also needed. I think what I have now is correct, but I was testing this on unclustered data which might change the results.

**Comment by matthieugomez** [comment]
Thanks a lot!  I have just pushed a new commit with your changes. Could you test it? One thing that would be great is if you could add some tests in https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/test/reg.jl, with the examples you used to compare with R.

**Comment by junder873** [comment]
I am a little new to Github, otherwise, I would just submit the changes there. Here are the tests I came up with, they all appear to pass.
```julia
# in R: summary(lm(y ~ x1 + w, data=df))
m = @model y ~ x1 + w
x = reg(df, m)
@test x.F ≈ 79.091576 atol = 1e-4

# Test P Value
# in R: summary(lm(w ~ z1, data=df))
m = @model w ~ z1
x = reg(df, m)
@test x.p ≈ 0.003998718283554043 atol = 1e-4
# in R: summary(lm(w ~ z1 + x1, data=df))
m = @model w ~ z1 + x1
x = reg(df, m)
@test x.p ≈ 3.369423076033613e-14 atol = 1e-4
```

It appears the issue was that the original model worked as long as there was one coefficient, so this test just adds another.

**Comment by matthieugomez** [comment]
Awesome! Thanks a lot for your help. I'm tagging a new version with the fix:
https://github.com/JuliaRegistries/General/pull/767
