### ISSUE TITLE
Update to StatsModels 0.6.0

### ISSUE THREAD

**Issue by grandemundo82** [FixedEffects/FixedEffectModels.jl#61]
When I run using FixedEffectssModels I get the following error:

WARNING: could not import StatsModels.Formula into FixedEffectModels
WARNING: could not import StatsModels.Terms into FixedEffectModels
WARNING: could not import StatsModels.evalcontrasts into FixedEffectModels
WARNING: could not import StatsModels.check_non_redundancy! into FixedEffectModels

It happens just after the last update of StatsModels

Please help

**Comment by matthieugomez** [comment]
I still need to update to StatsModels 0.6.0 (help welcome!). In the meantime, I have put an upper bound on StatsModels.

**Comment by matthieugomez** [comment]
See also https://github.com/JuliaStats/StatsModels.jl/issues/124

**Comment by matthieugomez** [comment]
Painfully done https://github.com/matthieugomez/FixedEffectModels.jl/commit/466e8f0d5e1e48627871c33d6c21a8ce248db7f9
