### ISSUE TITLE
Use a larger data set for benchmark

### ISSUE THREAD

**Issue by waynelapierre** [FixedEffects/FixedEffectModels.jl#63]
For the comparison of performance between FixedEffectModels, reghdfe and felm, could you use a larger data? I use the felm a lot on data with more than 1 million rows and 10 columns, I am curious how FixedEffectModels performs on larger data.

**Comment by matthieugomez** [comment]
I already do it for a dataset with 10 million rows, right?
https://github.com/matthieugomez/FixedEffectModels.jl/blob/master/benchmark/benchmark.jl
