### ISSUE TITLE
Get number of clusters in model metadata

### ISSUE THREAD

**Issue by grantmcdermott** [FixedEffects/FixedEffectModels.jl#65]
Apologies if I missed it, but is there a way to get/view the number of clusters from a model that's been run? 

This would be a nice feature to add to the model metadata, especially given the "smallest-length" adjustment for multiway clusters (https://github.com/matthieugomez/FixedEffectModels.jl/pull/50). 

Ideally, this information could then referenced by [RegressionTables.jl](https://github.com/jmboehm/RegressionTables.jl) too, since most journals like to see the number of clusters reported in your regression tables.

**Comment by matthieugomez** [comment]
You can now get it with the field `vcov_expr`

**Comment by grantmcdermott** [comment]
Just checking: Does the `vcov_expr` field still exist? 

I was expecting the following to work, but it doesn't.

```julia
using DataFrames, RDatasets, FixedEffectModels
df = dataset("plm", "Cigar")
mod1 = reg(df, @formula(Sales ~ NDI + fe(State) + fe(Year)), Vcov.cluster(:State), weights = :Pop)

## Get no. of clusters (here: equal to number of States)
mod1.vcov_expr
# ERROR: type FixedEffectModel has no field vcov_expr
# Stacktrace:
# [1] getproperty(::Any, ::Symbol) at ./Base.jl:20
```

**Comment by matthieugomez** [comment]
Sorry the field would be vcov_type now. It returns the argument passed by
the user.
I wrote a pull request in Statsbase to create a function called
covariance_estimator that would return it for any model.
https://github.com/JuliaStats/StatsBase.jl/pull/530

**Comment by grantmcdermott** [comment]
Thanks Matthieu. 

To clarify (since I just tried `vcov_expr` and it didn't quite give what I was expecting): 

My original request was to get the number of cluster _units_. In the case of the above regression, the answer would be trivially 46, because there are 46 unique states in our clustering variable "State". In the case of multiway, clustering, however, the number of units may not be trivial because of smallest length cluster adjustments, nested FEs, etc.

Again, apologies if I'm missing something or if I just wasn't clear the first time around. The model that I'm thinking of following here is based on the output from Stata's reghdfe. For example, if I ran `. reghdfe price weight length, absorb(rep78) vce(cluster rep78 foreign)` in Stata, part of the output would include:
```
[...]
Number of clusters (rep78)   =          5         [...]
Number of clusters (foreign) =          2         [...]

                          (Std. Err. adjusted for 2 clusters in rep78 foreign)

[...]

Absorbed degrees of freedom:
-----------------------------------------------------+
 Absorbed FE | Categories  - Redundant  = Num. Coefs |
-------------+---------------------------------------|
       rep78 |         5           5           0    *|
-----------------------------------------------------+
* = FE nested within cluster; treated as redundant for DoF computation
```
Of course, you may not want the output to be nearly as verbose as this. But I do think the effective clustering level of 2 in particular is valuable information. At least, this something journals / referees ask for in my experience.

**Comment by matthieugomez** [comment]
Oh I understand the question now! Let me think about it.

**Comment by matthieugomez** [comment]
You can now get a namedtuple with `mod1.nclusters`.
