### ISSUE TITLE
Benchmark of FixedEffectModels versus lfe in MRO

### ISSUE THREAD

**Issue by waynelapierre** [FixedEffects/FixedEffectModels.jl#67]
I was wondering if you could add a benchmark of FixedEffectModels versus lfe in Microsoft R Open instead of GNU R. Microsoft R Open uses MKL and I would like to see if FixedEffectModels is still faster than lfe with MKL support.

**Comment by matthieugomez** [comment]
I don't have access to this (I'm on Mac). Feel free to add your own benchmark if you can. In any case, I don't think it will change anything — the actual matrix computation `X'X \ X'y` accounts for a very small share of the total time.
