### ISSUE TITLE
Horizontal lines in REPL prompt in Juno

### ISSUE THREAD

**Issue by bjornerstedt** [FixedEffects/FixedEffectModels.jl#68]
FixedEffectModels changes the prompt in the REPL in Juno. I get the prompt with three horizontal lines:

````
julia> ======================================================================
----------------------------------------------------------------------
======================================================================
````

When run in a terminal this does not happen. I believe this might be due to lines 175, 178 and 186 in RegressionResult.jl, where `println("=" ^totalwidth)` should be `println(io, "=" ^totalwidth)`.

**Comment by matthieugomez** [comment]
Oops sorry. Can you do the pull request? I don’t have a computer on me but
I can accept it.
