### ISSUE TITLE
Changed meaning of .+= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [FixedEffects/FixedEffectModels.jl#7]
Your code uses `x .+= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .+ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.+` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in `widths .+= 1`, where `widths` is an array that it looks okay to mutate, but if it is a problem to mutate `widths` you can always change it to `+=`.

**Comment by matthieugomez** [comment]
Thanks for the heads up. As you say, works fine in my case.
