### ISSUE TITLE
New syntax for adding FEs

### ISSUE THREAD

**Issue by grantmcdermott** [FixedEffects/FixedEffectModels.jl#74]
Hi Matthieu,

I was just playing around with the new syntax for adding fixed effects. I was somewhat surprised to discover that the following doesn't work:
```
reg(df, @model(y ~ x + fe(fe1 + fe2), vcov = cluster(c1)))
``` 
Instead, you have to specify the fixed effects as separate "fe()" arguments:
```
reg(df, @model(y ~ x + fe(fe1) + fe(fe2), vcov = cluster(c1)))
```
No doubt your decisions have been shaped by some upstream package changes. But I do think the former approach is cleaner and more intuitive from a user perspective. Especially since it is consistent with the syntax for adding clusters, which can by combined within the same "cluster()" argument, i.e. `vcov = cluster(cl1 + cl2)`. 

Is there a technical reason that you didn't adopt the former approach? If not, would you consider, say, an alias on the back-end that makes it valid model code?

**Comment by matthieugomez** [comment]
Thanks for the feedback. 

The issue with the past syntax (or your suggested syntax) is that things like `id&year` are ambiguous: it's not clear whether the user wants id x year dummies, or id dummies multiplied by year. In the pas, I avoided this ambiguity by requiring users to convert all fixed effect variables to categorical. I personally found this to be cumbersome. 

With the new syntax, there is no ambiguity: one is written `fe(id)&fe(year)`, the other `fe(id)&year`.

**Comment by grantmcdermott** [comment]
A fair point. 

It's entirely your prerogative, of course, but perhaps I'll just close out this issue by saying: As a user I'd be very happy for any `fe(id + year)` type arguments to default to `fe(id) + fe(year)`. Similarly, for `fe(id&year)` to default to `fe(id)&fe(year)`. This could be documented in the README, with a reference to your `fe(id)&year` example for anyone specifically looking for id dummies multiplied by year.

(FWIW, this would be keeping in the same spirit as, say, lfe and reghdfe, which both automatically coerce variables in the FE slot to categorical.)

Anyway, just a thought. This package just seems to go from strength to strength. It has brought me back to Julia after a long absence. (I'm excited to try the GPU implementation.) I'm still too rusty to issue any PRs myself, but hopefully once my confidence returns!
