### ISSUE TITLE
UndefVarError: eachcol not defined

### ISSUE THREAD

**Issue by ThomasBourany** [FixedEffects/FixedEffectModels.jl#75]
Cher Matthieu, 

I have an issue with some incompatibilities btw different packages and FixedEffectModels
The one I can't solve gives me the following error : 

reg(data, @formula(Y ~ A + L + K)) ## very basic ahah
ERROR: UndefVarError: eachcol not defined
Stacktrace:
 [1] evalcontrasts(::DataFrame, ::Dict{Any,Any}) at /Users/thomasbourany/.julia/packages/StatsModels/pBxdt/src/modelframe.jl:124
 [2] #ModelFrame2#6(::Dict{Any,Any}, ::Function, ::StatsModels.Terms, ::DataFrame, ::BitArray{1}) at /Users/thomasbourany/.julia/packages/FixedEffectModels/9HKQv/src/formula/formula_iv.jl:94
 [3] #ModelFrame2 at ./none:0 [inlined]
 [4] #reg#30(::Nothing, ::Expr, ::Nothing, ::Nothing, ::Int64, ::Dict{Any,Any}, ::Float64, ::Int64, ::Bool, ::Symbol, ::Bool, ::typeof(reg), ::DataFrame, ::Formula) at /Users/thomasbourany/.julia/packages/FixedEffectModels/9HKQv/src/reg.jl:160
 [5] reg(::DataFrame, ::Formula) at /Users/thomasbourany/.julia/packages/FixedEffectModels/9HKQv/src/reg.jl:48
 [6] top-level scope at none:0

I think it has something to do with Compat (before it gave me the following error: 
WARNING: both DataFrames and Compat export "eachcol"; uses of it in module StatsModels must be qualified) but now that I removed Compat (and GLM that was using Compat as well, with pkg.rm())

- Moreover, when I add fixed effect (as in your examples) it gives me :
ERROR: MethodError: no method matching length(::Expr)
- When I add the clustering, it even spits out this: 
ERROR: UndefVarError: Vcov not defined
reg(data, @formula(Y ~ L + K + fe(time_t) + fe(firm_st)), Vcov.cluster(:time_t, :firm_st))

I feel the three points are linked!

Also, there was an incompatibility with MixedModels that prevented me to even add the package. But this problem was solved when I removed MixedModels

I have Julia v1.0.3 and I also updated most of my packages beforehand. 
Sorry if it is something trivial, 
Thanks, Merci beaucoup!

**Comment by matthieugomez** [comment]
The current version of FixedEffectModels, with the syntax explained in the README, works for Julia 1.1. (and above). It'd a bit hard for me to make sure that it works for versions of Julia below 1.1.

**Comment by matthieugomez** [comment]
Ok I've modified the package to allow Julia 1.0

If you try
```
]add FixedEffects#master
]add FixedEffectModels#master
```
everything should work. Let me know if not

**Comment by ThomasBourany** [comment]
Oh thank you for your quick response, 

Unfortunately, it doesn't seem to work. After removing Pkg.rm(), I added the 1st folder (fixed effects) and adding the 2nd one gives me this error: 

(v1.0) pkg> add FixedEffectModels#master
  Updating git-repo `https://github.com/matthieugomez/FixedEffectModels.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StatsModels [3eaba693]:
 StatsModels [3eaba693] log:
 ├─possible versions are: [0.3.0-0.3.1, 0.4.0, 0.5.0, 0.6.0-0.6.6] or uninstalled
 ├─restricted to versions 0.6.0-0.6 by FixedEffectModels [9d5cd8c9], leaving only versions 0.6.0-0.6.6
 │ └─FixedEffectModels [9d5cd8c9] log:
 │   ├─possible versions are: 0.9.3 or uninstalled
 │   └─FixedEffectModels [9d5cd8c9] is fixed to version 0.9.3
 └─restricted to versions 0.5.0 by an explicit requirement — no versions left

This error carries on even when I add the package  -- Pkg.add("FixedEffectModels") -- behorehand.

**Comment by matthieugomez** [comment]
Yes you need to update to StatsModels 0.6.
Did you try ]update?
If it does not work you probably have a package that is not compatible with
StatsModels 0.6, and therefore with the current version of
FixedEffectModels.

**Comment by ThomasBourany** [comment]
Ok, I think I figured out part of it: 
For some reasons, ]update and Pkg.update() were not updating StatsModels from 0.5 to 0.6.6,  
After Pkg.rm("FixedEffectModels"), it also removed StatsModels 0.5, and I could add the most recent one: 
pkg> add StatsModels@0.6

In this case, I could have added FixedEffectModels#master

However, the error remains when using regression with or without fixed effects -- the error is exactly the same as in my first post above. 
reg(data, @formula(Y ~ A + L + K)) 

I think I'll download Julia 1.1. in the near future ! 
Thanks !
