### ISSUE TITLE
Threads?

### ISSUE THREAD

**Issue by jmboehm** [FixedEffects/FixedEffectModels.jl#95]
Hi,
For some reason I can't get `reg` to run on multiple threads anymore. Looking at FixedEffects.jl, it seems threads are still supported, no? Is that the default when using `method = :cpu`?
My `nthreads()` says 4 and I'm running 
```julia
using DataFrames, FixedEffectModels
df = DataFrame(y = rand(Float64, 1_000_000), x = rand(Float64, 1_000_000), g = rand(0:10,1_000_000))
categorical!(df, :g)
reg(df, @formula(y ~ x + fe(g)))
```
on Julia 1.3 and 1.4 with FixedEffectModels.jl 0.10.5 and FixedEffects 0.7.0.

**Comment by matthieugomez** [comment]
It should always use multiple threads. How do you know it's not using multiple threads?

**Comment by jmboehm** [comment]
Now that you say it I'm not sure it's the right thing to look at, but my CPU utilization never exceeds 20% (and everything is on one process). A regression that used to take 1-2h in the past (specifically, on 0.7.4) is still not done after 5h. If you think it's unrelated to threads, I'll go back to 0.7.4 and compare.

**Comment by matthieugomez** [comment]
Thanks!
I did change how multithreading works.  In previous versions, multithreading was used to demean each variable in a separate thread.  In the current version, each variable is demeaned using multiple threads. The current version is more elegant, I think, but maybe it makes the package slower.

- Could you open an issue in FixedEffects asking to revert to the previous one? I would be interested to know how many regressors and fixed effects you have in the regression.
- When you talk about CPU utilization, is it CPU utilization for the regression that takes 1-2h? If so, it's certainly surprising you don't find something higher than 100%. On my mac with 12 threads, in Activity Monitor, I do see Julia CPU utilization around 1000% for regressions that take more than a few seconds.

**Comment by jmboehm** [comment]
Sorry, I think this is in fact unrelated to threads. I tried it on FixedEffectModels 0.7.4 and FixedEffects 0.1.2, without `lsmr_threads`, and the CPU utilization is similarly at about 20%.

Still:

On FixedEffectModels 0.7.4 and FixedEffects 0.1.2 and the following regression takes about half an hour:
```
@time rr1s1 = reg(df, @model(Y ~ X1 + X2, 
    fe = FP_CAT + PY_CAT*DIV2_TL1 + PY_CAT*DIV2_TL1_DR), save = :residuals)
```
where variables that end with `_CAT` are categorical, the others are continuous.
On 0.10.5 and FixedEffects 0.7.2 I run
```
@time rr1s1 = reg(df, @formula(Y ~ X1 + X2 
    + fe(FP_CAT) + fe(PY_CAT)&DIV2_TL1 + fe(PY_CAT)&DIV2_TL1_DR), save = :residuals)
```
and it didn't even finish overnight.

Both are on the same data (46m obs, FP_CAT has 17.4m levels, PY_CAT has 11.3k levels). I guess in the second specification I should also add `fe(PY_CAT)` to have the categorical variable by itself, as in the first specification-- but if anything this omission should make it faster.

Am I doing something wrong in the specification?

**Comment by matthieugomez** [comment]
I looks like the specifications are different. You should use * in both.

**Comment by jmboehm** [comment]
Thanks a lot; I'll try that and report back. By the way, `*` is undocumented in 0.10.5.

**Comment by matthieugomez** [comment]
Sorry about that. Does this pull request clarify things?
https://github.com/FixedEffects/FixedEffectModels.jl/pull/96

**Comment by jmboehm** [comment]
Perfect, thanks. In case the `*` does not resolve the difference, I'll try to construct a MWE and open a new issue.
