### ISSUE TITLE
Memory Error with Missing Data and IV

### ISSUE THREAD

**Issue by junder873** [FixedEffects/FixedEffectModels.jl#99]
When I run a regression that includes instrumental variables and missing data I run into out of memory errors very often. It also seems to happen regardless of where the missing values are (I tried to replicate this with the Cigar dataset, but it seems to require lots of missing data points and a larger dataset, I have memory issues with ~67000 observations and ~600 missing data points).

Simply running a dropmissing on the dataset beforehand solves the issue completely, but I am not sure why this happens. Even after the error, the memory usage in Julia remains high, suggesting it might be a memory leak error of some type.

I have been playing around with the movie dataset, I will continue to do so and hopefully post some code that replicates this issue with data.

**Comment by matthieugomez** [comment]
What do you mean by memory errors?

Definitely let me know if you can find a replicable example. Maybe send me the dataset with the code to reproduce the error?

**Comment by matthieugomez** [comment]
Thanks! solved by https://github.com/FixedEffects/FixedEffectModels.jl/pull/100
